import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Bug } from 'lucide-react';
import Navbar from './components/Navbar'; import RouteForm from './components/RouteForm'; import MapView from './components/MapView'; import SafetyInfo from './components/SafetyInfo'; import SOSButton from './components/SOSButton'; import Loader from './components/Loader'; import RouteOptions from './components/RouteOptions';
const API_URL=import.meta.env.VITE_API_URL||'http://localhost:8000';
const distance=(a,b)=>{const r=Math.PI/180,x=(b.lat-a.lat)*r,y=(b.lon-a.lon)*r;return 6371000*Math.sqrt(x*x+Math.cos(a.lat*r)*Math.cos(b.lat*r)*y*y)};
export default function App(){const [form,setForm]=useState({city:'Chennai',source:'Anna Nagar, Chennai',destination:'Avadi, Chennai'}),[data,setData]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[userLocation,setUserLocation]=useState(null),[selectedId,setSelectedId]=useState('safest'),[alert,setAlert]=useState(null),[debug,setDebug]=useState(false);const selected=useMemo(()=>data?.routes?.find(r=>r.id===selectedId)||data?.best_route,[data,selectedId]);
useEffect(()=>{if(!navigator.geolocation)return;const id=navigator.geolocation.watchPosition(p=>setUserLocation({lat:p.coords.latitude,lon:p.coords.longitude}),()=>setAlert({type:'warn',text:'Location is unavailable. Enable location access for live safety guidance.'}),{enableHighAccuracy:true,maximumAge:8000,timeout:12000});return()=>navigator.geolocation.clearWatch(id)},[]);
useEffect(()=>{if(!userLocation||!selected)return;const nearest=Math.min(...selected.coordinates.map(([lat,lon])=>distance(userLocation,{lat,lon})));const zone=selected.risk_segments?.find(s=>distance(userLocation,{lat:(s.start[0]+s.end[0])/2,lon:(s.start[1]+s.end[1])/2})<250&&s.risk>=6);if(zone)setAlert({type:'danger',text:'⚠️ Entering unsafe area. Consider continuing on the green route.'});else if(nearest>120)setAlert({type:'warn',text:'You are moving away from the safe route.'});else setAlert({type:'safe',text:'You are on a safe path.'})},[userLocation,selected]);
function chooseRoute(id){setSelectedId(id);setAlert(id==='safest'?{type:'safe',text:'Green route selected: lower risk and better safety coverage.'}:{type:'warn',text:'This route may pass through higher-risk areas.'})}
async function findRoute(e){e.preventDefault();setLoading(true);setError('');setData(null);try{const response=await fetch(`${API_URL}/get_safe_route`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source:form.source,destination:form.destination})});const json=await response.json();if(!response.ok)throw new Error(json.detail||'Unable to analyze route');setData(json);setSelectedId('safest');setAlert({type:'safe',text:'We recommend the GREEN route as it has lower risk and better safety coverage.'})}catch(err){setError(err.message)}finally{setLoading(false)}}
return <div className="min-h-screen bg-[#f7faf8]"><Navbar/><main className="grid min-h-[calc(100vh-64px)] lg:grid-cols-[390px_1fr]"><aside className="p-5 md:p-7 lg:border-r border-slate-100"><div className="panel"><p className="eyebrow">Plan a safer journey</p><h1>Move with more <em>confidence.</em></h1><p className="intro">Compare route choices using live coverage and segment-level risk.</p><RouteForm form={form} setForm={setForm} onSubmit={findRoute} loading={loading}/></div>{loading&&<div className="mt-4"><Loader/></div>}{error&&<div className="error">{error}</div>}{data&&<><RouteOptions routes={data.routes} selectedId={selectedId} onSelect={chooseRoute}/><button className={'debug-toggle '+(debug?'on':'')} onClick={()=>setDebug(!debug)}><Bug size={15}/>Debug: segment risk {debug?'on':'off'}</button></>} {alert&&<div className={'nav-alert '+alert.type}><AlertTriangle size={16}/>{alert.text}</div>}<div className="mt-4"><SafetyInfo route={selected} tracking={!!userLocation&&!!data}/></div></aside><section className="relative min-h-[520px] p-5 pl-0 max-lg:px-5 max-lg:pt-0 lg:p-7 lg:pl-0"><MapView routes={data?.routes} source={data?.source} destination={data?.destination} userLocation={userLocation} selectedId={selectedId} onSelect={chooseRoute} debug={debug}/></section></main><SOSButton location={userLocation}/></div>}
